version: '2.2'
services:
  jasu:
    image: sysnetcz/opendata-jasu:1.0.1
    container_name: jasu
    environment:
      - ES_HOST_NAME=elasticsearch
      - ES_PORT=9200
      - TZ=Europe/Prague
    volumes:
      - ./data:/opt/opendata/data
      - ./config:/opt/opendata/conf
    networks:
      - default
    ports:
      - 127.0.0.1:8080:8080

networks:
  default:
    external:
      name: ${EXTERNAL_NETWORK}
